# ================================================ #
#   _           _        _   _                 ____ _
#  \ \        / /       | | | |              / ____| |
#   \ \  /\  / /__  __ _| |_| |__   ___ _ __| |    | |__   __ _ _ __   __ _  ___
#    \ \/  \/ / _ \/ _` | __| '_ \ / _ \ '__| |    | '_ \ / _` | '_ \ / _` |/ _ \
#     \  /\  /  __/ (_| | |_| | | |  __/ |  | |____| | | | (_| | | | | (_| |  __/
#      \/  \/ \___|\__,_|\__|_| |_|\___|_|   \_____|_| |_|\__,_|_| |_|\__, |\___|
#                                                                      __/ |
#                                                                     |___/
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#                   Powered by Xylit
# ================================================ #
# SpigotDEV -> https://www.spigotmc.org/resources/authors/xylit.265936/
# BukkitDEV -> https://dev.bukkit.org/members/Xylit
# MinecronDEV -> https://dev.minecron.de/user/Xylit (Coming Soon)
# Maxcron -> https://maxcron.de/user/Xylit (Coming Soon)



# Which Language dou you want?
# You can add your own Language in the lang.yml
language: en



# ========================
#       Permissions
# ========================

# /stats -- Shows your own Stats
PermissionRain: "OreStats"

# /stats [Player] -- Shows stats from other Players
Permission: "OreStats.other"




